# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Papr' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Papr
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'Moya'
  pod 'RxOptional'
  pod 'ModelMapper'
  pod 'p2.OAuth2'

end
