# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Papr' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  # RxSwift
  
  pod 'RxSwift', '4.1.2'
  pod 'RxCocoa', '4.1.2'
  pod 'RxDataSources', '3.0.2'
  pod 'RxOptional', '3.3.0'
  pod 'Action', '3.5.0'
  pod 'NSObject+Rx', '4.2.0'
  
  # Network
  pod 'Moya', '10.0.2'

  # Keychain
  pod 'KeychainSwift', '10.0.0'
  
  # Image
  pod 'Nuke', '6.0' 

  # Pods for Papr

  target 'PaprTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PaprUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
